/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DeadManSwitchInterface extends Interface {
  getFunction(
    nameOrSignature: "Alive" | "still_alive" | "transferFunds"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "Alive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "still_alive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "Alive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "still_alive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFunds",
    data: BytesLike
  ): Result;
}

export interface DeadManSwitch extends BaseContract {
  connect(runner?: ContractRunner | null): DeadManSwitch;
  waitForDeployment(): Promise<this>;

  interface: DeadManSwitchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  Alive: TypedContractMethod<[], [boolean], "view">;

  still_alive: TypedContractMethod<[], [void], "nonpayable">;

  transferFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "Alive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "still_alive"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
