/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deadmanSwitchSol from "./DeadmanSwitch.sol";
export type { deadmanSwitchSol };
import type * as lockSol from "./Lock.sol";
export type { lockSol };
export * as factories from "./factories";
export type { DeadManSwitch } from "./DeadmanSwitch.sol/DeadManSwitch";
export { DeadManSwitch__factory } from "./factories/DeadmanSwitch.sol/DeadManSwitch__factory";
